[package]
name = "iamgroot"
version = "0.1.5"
edition = "2021"
description = "Rust code generation from Open-RPC spec"
license = "MIT"

[features]
default = []
anyhow = ["dep:anyhow"]

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = {version = "2.2.2", features = ["serde"]}
once_cell = "1.17.1"
regex = "1.7.1"
anyhow = { version = "1.0.71", optional = true }
pretty_assertions = "1.4.0"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
