[package]
name = "iamgroot"
version = "0.1.2"
edition = "2021"
description = "Rust code generation from Open-RPC spec"
license = "MIT"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.17.1"
regex = "1.7.1"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
